### ISSUE TITLE
Mixins could communicate core configuration back to Porter

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#1011]
Another value add of mixins would be the ability to communicate back to porter more advanced configuration.

For example the docker-compose mixin could handle telling porter that it requires the docker extension.  Instead of this:

```yaml
mixins:
- docker-compose

required:
- docker
```

a user could simplify down to only 

```yaml
mixins:
- docker-compose
```

and the docker-compose mixin would handle during build telling porter about the required docker extension.

Another example could be the terraform mixin:

```yaml
mixins:
- terraform

outputs:
- name: tf_state
  path: /cnab/outputs/tf_state
  ...
```

The terraform mixin by default outputs a statefile, unless configured otherwise in the mixin configuration section, and so would communicate to porter during build that it will generate a bundle output `tf_state`:

```yaml
mixins:
- terraform
```

We should do some thinking about this before assuming that it should be done because it may not be the best idea (just an example of what a mixin _could_ tell Porter). I'm concerned that it would reduce what is in the porter.yaml at the expense of clarity. Likely you would need a second command to render or preview the full porter.yaml with what the mixins inject to see what is really going on. If that's necessary, is this feature helpful or ultimately harmful?
