### ISSUE TITLE
Generate parameter sources for outputs from the bundle templating

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#1067]
When we build a bundle, look for templating that uses `bundle.outputs.*` and create parameter source definitions in the bundle.json to match.

The following porter.yaml:

```yaml
install:
  - exec: "Create MySQL"
      command: ./install.sh
    outputs:
      - name: connstr
         jsonPath: ...

upgrade:
  - exec: "Upgrade MySQL"
      command: ./upgrade.sh
      arguments:
      - "{{ bundle.outputs.connstr }}"

outputs:
  - name: connstr
     type: string
     applyTo: [ "install" ]
```

should yield the following bundle.json

```json
{
    "custom": {
      "io.cnab.parameter-sources": {
        "porter-connstr-output": {
          "priority": ["output"],
          "sources": {
            "output": {
              "name": "connstr"
            }
          }
        }
      }
    },
    "parameters": {
      "porter-connstr-output": {
        "applyTo": [ "upgrade", "uninstall" ],
        "definition": "connstr-output",
        "destination": { "env": "PORTER_CONNSTR_OUTPUT" },
        "required": false
      }
    }
}
```

Alternatively the output could be used directly to default a parameter (in a later release) DEFERRED
```yaml
parameters:
- name: connection-string
  type: string
  applyTo: ["upgrade"]
  source:
    output: connstr

install:
  - exec: "Create MySQL"
      command: ./install.sh
    outputs:
      - name: connstr
         jsonPath: ...

upgrade:
  - exec: "Upgrade MySQL"
      command: ./upgrade.sh
      arguments:
      - "{{ bundle.parameters.connection-string }}"

outputs:
  - name: connstr
     type: string
     applyTo: [ "install" ]
```

should yield the following bundle.json where a parameter is not auto-generated since the output is not used at runtime, and is ONLY used to default a user-defined parameter. If the output was used at runtime, then it must get a porter-ps-* parameter so that we can use it in our wiring.

```json
{
    "custom": {
      "io.cnab.parameter-sources": {
        "connection-string": {
          "priority": ["output"],
          "sources": {
            "output": {
              "name": "connection-string"
            }
          }
        }
      }
    }
}
```
