### ISSUE TITLE
Generate parameter sources for dependency outputs

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#1069]
When we build a bundle, look for templating that uses `bundle.dependencies.DEPENDENCY_NAME.outputs.*` and create parameter source definition of type `dependencies.output`

```yaml
dependencies:
  mysql:
    tag: getporter/mysql:v0.1.2

install:
  - exec: "Install Wordpress"
      command: ./install.sh
      arguments:
        - "{{ bundle.dependencies.mysql.outputs.root-password }}"
```

should yield the following bundle.json

```json
{
    "custom": {
      "io.cnab.parameter-sources": {
        "porter-connstr": {
          "priority": ["dependencies.output"],
          "sources": {
            "dependencies.output": {
              "name": "connstr"
            }
          }
        }
      }
    }
```

Otherwise beyond the different source type of the parameter, it should work the same as #1067 .

This requires an addition to the cnab spec to support `dependencies.output` which we should prove out here.
