### ISSUE TITLE
Handle applyTo properly for parameter sources, when the output doesn't exist yet

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#1159]
When a parameter has its source set to an output, there is a bit of an awkward question of how to handle the install action. The output won't exist yet. So either the user must supply a value for the install action, the author must make the parameter optional by setting a default or the bundle author must use applyTo to list all the actions except install.

One option is that porter can default the applyTo for authors when the parameter source is set to an output, excluding the install action, when the author hasn't set a default or applyTo themselves. If they wanted the parameter to be required on install, they would need to set applyTo explicitly.

Transforming this:

```yaml
parameters:
  - name: tfstate
    type: file
    path: config.json
    source:
      output: config.json
```

into this in the bundle.json

```yaml
parameters:
  - name: tfstate
    type: file
    path: config.json
    source:
      output: config.json
    applyTo:
      - upgrade
      - uninstall
```

This would let authors write what I think will come more naturally to them (most won't think about the install lacking the output edge case and want to list out the applyTo by hand and maintain it if they have custom actions).

**Comment by vdice** [comment]
Ah, an interesting problem for sure.  While I definitely like the approach of building for the common use case and in this scenario keeping the yaml config to a minimum, I still worry about the potential pitfall for users expecting the parameter (with source of type output) to apply to their custom actions (when/if they don't set up `applyTo` for the param) but it ends up being unapplied by Porter behind the scenes.

Perhaps instead of the bundle.json mod behind the scenes, we could add a bit of logic in the install action code to support circumventing the issue described above.  Maybe, `for each param that depends on a source of type output, unapply this param for this install action only`.  Like an "on-the-fly unapply" ™️ instead of manual/permanent updates to the bundle.json.

My other thought would be to introduce (even if behind the scenes and not in the manifest itself) the inverse of `applyTo`: `ignoreFor` or some such, to specify a subset of actions that the parameter should not apply to.

**Comment by carolynvs** [comment]
> I still worry about the potential pitfall for users expecting the parameter (with source of type output) to apply to their custom actions (when/if they don't set up applyTo for the param) but it ends up being unapplied by Porter behind the scenes.

Can we walk through that a bit to make sure I understand? This is what I was thinking for porter's defaulting of applyTo:

Porter will default the applyTo when:
* A source output is set AND
* No default is set AND
* No applyTo is set

The applyTo will be defaulted to all defined actions, built-in and custom, excluding install. If they need something more exciting than that then they need to define applyTo themselves. For instance, if they have a custom action that is intended to be executed _before_ install, they would need to define applyTo manually and also exclude it. I definitely see the use case for an exclude so that you could just say exclude "install" and "preflight" and not have to list everything. That would be an alternative way to do this, but I think this has merit as a default.

Here's an example that includes a custom action:

```yaml
name: wordpress
version: 0.1.0

mixins:
- terraform

parameters:
  - name: tfstate
    type: file
    path: /cnab/app/tfstate
    source:
      output: tfstate

outputs:
  - name: tfstate
     type: file
     path: /cnab/app/tfstate

install:
  - terraform:
       description: Install the world
       # this creates /cnab/app/tfstate

status:
  - terraform:
        description: Check up on world
        # this uses /cnab/app/tfstate

upgrade:
  - terraform:
       description: Upgrade world
       # this uses and updates the tfstate output

uninstall:
  - terraform:
     description: Sorry world
     # This uses and updates the tfstate output
```

The parameter written to the bundle.json would look like this:

```yaml
parameters:
  - name: tfstate
    type: file
    path: config.json
    source:
      output: config.json
    applyTo:
      - status
      - upgrade
      - uninstall
```

Do you think this would be a safe default as long as it was documented that by default source outputs exclude the install output and that you need to manually configure applyTo if you have custom actions that are meant to be executed before install?
