### ISSUE TITLE
Dependencies not installed via declared order?

### ISSUE THREAD

**Issue by vdice** [deislabs/porter#1243]
## Describe the bug
As of https://github.com/deislabs/porter/pull/1170, Porter should support ordered dependencies.  However, I'm seeing cases where the execution of dependencies does not follow the order declared in the manifest.

## To Reproduce
1. Run `porter install`
2. Use this porter.yaml:
```
name: deps-test
description: "A Porter bundle to exercise ordered dependencies"
tag: localhost:5000/deps-test
version: 0.1.0

mixins:
  - exec

credentials:
  - name: kubeconfig
    path: /root/.kube/config

dependencies:
  - name: nfs
    tag: vdice/nfs:v0.1.0

  - name: cowsay
    tag: vdice/cowsay:v0.1.0

install:
  - exec:
      description: "Install"
      command: sh

uninstall:
  - exec:
      description: "Uninstall"
      command: sh
```
4. While the manifest above declares `nfs` first, then `cowsay`, see below that the dependency `cowsay` is executed prior to `nfs`, the opposite of the intended order.
```
 $ porter install -c deps-test --force
Executing dependency cowsay...
executing install action from cowsay (installation: deps-test-cowsay)
Install Hello World
 ______________
< Hello World! >
 --------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
execution completed successfully!
Executing dependency nfs...
executing install action from nfs (installation: deps-test-nfs)
Helm Install NFS Provisioner
/usr/local/bin/helm3 helm3 install nfs stable/nfs-server-provisioner --version 1.1.1 --wait --values /cnab/app/chart-values.yaml
NAME: nfs
LAST DEPLOYED: Thu Sep  3 18:45:56 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The NFS Provisioner service has now been installed.

A storage class named 'nfs' has now been created
and is available to provision dynamic volumes.

You can use this storageclass by creating a `PersistentVolumeClaim` with the
correct storageClassName attribute. For example:

    ---
    kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: test-dynamic-volume-claim
    spec:
      storageClassName: "nfs"
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
execution completed successfully!
installing deps-test...
executing install action from deps-test (installation: deps-test)
Install
execution completed successfully!
```

## Notes

For repeated installations of the example bundle above, I have seen the dependencies installed in the order declared (first `nfs`, then `cowsay`), but on the next installation, the order will change.  Therefore, the ordering doesn't appear to be repeatable/dependable either?

## Expected behavior
I was expecting that the dependencies would be executed in the order declared in the manifest.  (Of course, for `uninstall`, I do expect the opposite.)

## Version

`porter v0.28.1-2-g10efa682 (10efa682)`
