### ISSUE TITLE
Missing name in generated bundle.json

### ISSUE THREAD

**Issue by garethr** [deislabs/porter#125]
```console
$ porter version
porter v0.1.0-ralpha.1+aviation (c86f6ab)
```

Using the following config.

```yaml
mixins:
  - exec

name: porter
version: 0.1.0
invocationImage: garethr/porter-hello:latest

install:
  - description: "Install Hello World"
    exec:
      command: bash
      arguments:
        - -c
        - echo Hello World

uninstall:
  - description: "Uninstall Hello World"
    exec:
      command: bash
      arguments:
        - -c
        - echo Goodbye World
```

This results in the following `bundle.json` when built:

```json
{
    "name": "",
    "version": "0.1.0",
    "description": "",
    "invocationImages": [
        {
            "digest": "sha256:3de9d00a78c1a4278d0ac1d6cf4d64b8df7924aba65758f15165e17431b96309",
            "imageType": "docker",
            "image": "garethr/porter-hello@sha256:3de9d00a78c1a4278d0ac1d6cf4d64b8df7924aba65758f15165e17431b96309"
        }
    ],
    "images": null,
    "parameters": {},
    "credentials": {}
}
```

Note the missing `name` field. I had expected this to be populated with the value from the `name` field from the `porter.yaml` config.
