### ISSUE TITLE
Can't pass source variables to the exec arguments list

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#158]
This was first implemented in https://github.com/deislabs/porter/issues/31 but doesn't seem to work anymore.

When you run this, replace TODO with your username.

```yaml
mixins:
  - exec

name: HELLO
version: 0.1.0
description: "An example Porter configuration"
invocationImage: TODO/porter-hello:latest

parameters:
  - name: cmd
    type: string
    default: "echo hello world"

install:
  - description: "Install Hello World"
    exec:
      command: bash
      arguments:
        - -c
        - source: bundle.parameters.cmd

uninstall:
  - description: "Uninstall Hello World"
    exec:
      command: bash
      arguments:
        - -c
        - echo Goodbye World
```

```console
$ porter build && duffle install FOO -f bundle.json --insecure
Executing install action...
executing porter install configuration from /cnab/app/porter.yaml
Install Hello World
Error: yaml: unmarshal errors:
  line 6: cannot unmarshal !!map into string
err: yaml: unmarshal errors:
  line 6: cannot unmarshal !!map into string
```

**Comment by nunix** [comment]
just for information, I got the exact same issue by running with porter only:
```bash
porter run --action install --file ./porter.yaml --debug
```

really looking forward to this fix :)

**Comment by jeremyrickard** [comment]
This turns out not to be a problem with the way the parameter sourcing is working, it's a "how go is parsing YAML" problem. You _can_ pass the params, with slightly different YAML right now. 

The yaml above fails (here it is again):

```
install:
  - description: "Install Hello World"
    exec:
      command: bash
      arguments:
        - -c
        - source: bundle.parameters.cmd
```

However.....this does work

```
install:
  - description: "Install Hello World"
    exec:
      command: bash
      arguments:
        - -c
        - "source: bundle.parameters.cmd"
```

When the YAML blob gets loaded to process, it's failing to handle that correctly. Working on a fix now.
