### ISSUE TITLE
Design: Think about how to "lock in" external artifacts at build time

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/porter#202]
👵 Picture it! Colorado, 2019. A bundle author wants to use the Helm mixin with a stable chart or the Kubernetes mixin with some manifests on the internet. As a user of Porter, they'd like to have those files sucked into the invocation image so all the goodness of signed bundle and digested invocation images apply to the manifests as well. 

Currently, at build time we don't pass the YAML of the step down to the mixin. We should think about how we can pass all the relevant step YAML down so that the mixins could be smart enough to go and fetch the external resources and rewrite the `porter.yaml` to reflect those inside the bundle.

**Comment by carolynvs** [comment]
The action commands pass in the yaml step data. So one idea would be to do something similar for build. When a `mixin build` is called, porter looks for all the steps for that mixin and passes them in on stdin.

For example, for this manifest:

```yaml
mixins:
- helm

install:
- helm:
  ...
- exec:
  ...

upgrade:
- helm:
  ...
```

The mixin would get the following on stdin for `helm build`:

```yaml
install:
- helm:
  ...

upgrade:
- helm:
  ...
```
