### ISSUE TITLE
Design: HTTP mixin

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#256]
It would be useful to have an HTTP mixin that could talk to an endpoint to submit and receive data.

```
install:
- http:
    get: https://example.com/${bundle.parameters.thing}
    outputs:
    - name: thingie
       path: body[0].firstChild().randojsonpaththing...
```
