### ISSUE TITLE
Provide mixin steps to mixin during build

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#262]
When a mixin is run, we provide the step mixin to it knows what to do. But when we ask the mixin to provide the lines for the Dockerfile, we don't give it any context from the steps it will be asked to run.

Depending on the mixin, it would really help it to know what it's going to need to do at runtime. So we should pass in a list of all the steps associated with it on STDIN and let the mixin use that information to maybe do extra work during build.

Here is an example of what the data will look like that is passed to the mixin on STDIN:

```yaml
install:
- helm:
    description: install mysql
    chart: stable/mysql
    ...
- helm:
    description: install wordpress
    ...
uninstall:
- helm:
    description: uninstall wordpress
    ...
```
