### ISSUE TITLE
Mustache concatenation (ref #161)

### ISSUE THREAD

**Issue by nunix** [deislabs/porter#305]
Hi team,
I just tried a quick concatenation as follow:
```
install:
  - exec:
      description: "===PORTER DEP=== Creates a container based on the image"
      command: 
        source: bundle.parameters.DOCKER_SOURCE
      arguments:
        - run
        - -d
        - --name "{{ bundle.parameters.DISTRO_NAME }}"
        - "{{ bundle.parameters.DISTRO_IMAGE }}:{{ bundle.parameters.DISTRO_VERSION }}"
        - /bin/sh
```

while it does renders it correctly, I have the following error:
```
Error: could unmarshal input:
 install:
- exec:
    arguments:
    - run
    - -d
    - --name "wslubuntu"
    - ubuntu:19.04
    - /bin/sh
    command:
      source: bundle.parameters.DOCKER_SOURCE
    description: ===PORTER DEP=== Creates a container based on the image
: yaml: unmarshal errors:
  line 9: cannot unmarshal !!map into string
```

I don't know if it's my syntax which is wrong or if it's on "porter side".

Thanks a lot for the help
Nuno

**Comment by carolynvs** [comment]
One thing that jumps out at me is that there is still the old `source: ` templating fragment being used for the `command` field. Would you please try changing it to the following and running it again?

```
install:
  - exec:
      description: "===PORTER DEP=== Creates a container based on the image"
      command: "{{ bundle.parameters.DOCKER_SOURCE }}"
      arguments:
        - run
        - -d
        - --name "{{ bundle.parameters.DISTRO_NAME }}"
        - "{{ bundle.parameters.DISTRO_IMAGE }}:{{ bundle.parameters.DISTRO_VERSION }}"
        - /bin/sh
```
