### ISSUE TITLE
Let bundles provide credential hints

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#326]
It would be super useful if a bundle could provide hints about the credentials it wants, such suggested defaults on where to find the values and explanatory text for what the credential is.

```yaml
credentials:
- name: kubeconfig
  path: /root/.kube/config
  default: ~/.kube/config
  description: File with embedded server and user certificates to connect to a kubernetes cluster. Helm should have already been init'd on this cluster.
- name: SUBSCRIPTION_ID
  env: AZURE_SUBSCRIPTION_ID
```
