### ISSUE TITLE
[Bug] The upgrade function always runs twice

### ISSUE THREAD

**Issue by nunix** [deislabs/porter#386]
hi Team,

for some unknown reason, the `upgrade` function inside a bundle will run twice.
Here are my environment details:
Porter version: **porter v0.7.0-ralpha.1+englishrose (83471fb)**
Context: full CNAB (not my WSL hybrid version)
Porter upgrade function:
```
upgrade:
  - exec:
      description: "check the K3s cluster status"
      command: bash
      arguments:
        - -c
        - "k3d {{ bundle.parameters.k3dcommand }}"
```

Reproduction steps:
porter build -- OK
porter install -- OK
porter upgrade -- Runs twice
porter uninstall -- OK

Screenshot of output:
![image](https://user-images.githubusercontent.com/905874/58983484-35181580-87d7-11e9-8727-c6a45973245f.png)

I can provide more information if needed 😄 

Thanks a lot and be ready for the next demo 😈 

The Corsair
