### ISSUE TITLE
Bug: workdir not set in invocation image

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/porter#388]
The working directory is not set in the invocation image, so it defaults to /. This makes it difficult to use relative paths to reference things like manifests:

```yaml
install:
  - kubernetes:
      description: "Create NGINX Deployment"
      manifests:
        - manifests/kubernetes
```

In this case, currently Porter is running from the root directory so it doesn't have the context of /cnab/app that we would expect from the automagical copy. We should fix this so people can rely on this and not need to know about the actual directory structure in the image (aside from anything relative to the porter.yaml)
