### ISSUE TITLE
Write dependencies to bundle.json on build

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#429]
Now that the cnab spec supports dependencies, when we generate the bundle.json we should populate the dependencies section of the bundle.json file

https://github.com/deislabs/cnab-spec/blob/master/500-CNAB-dependencies.md#dependencies-metadata

This relies on https://github.com/deislabs/cnab-go/issues/35 which we can tackle after the cnab-go 1.0 release.

This is going to require changes to the porter.yaml manifest to support specifying the bundle version for a dependency.

```yaml
dependencies:
- name: mysql
  tag: deislabs/azure-mysql:5.7
```

```yaml
dependencies:
- name: mysql
  tag: deislabs/azure-mysql
  versions:
   - 5.7.x - 6.3.x
   - 6.5.x - 6.8.x
   prereleases: true
```

We will handle smooshing version and versions into version.ranges and prereleases under version on the bundle.json representation.

Other fields on the dependency, such as parameters and connections, are not written to bundle.json.
