### ISSUE TITLE
parameters use destination but credentials don't

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#490]
It's confusing that when specifying where a parameter / credential should dump it's value into the bundle, they do it in different ways in the porter.yaml

```yaml
parameter:
- name: pony
  destination:
    env: STABLE

credentials:
- name: dog
   env: HOUSE
```

One uses destination explicitly and the other doesn't. It would be helpful if we could pick if we want to use destination or not, and use it the same between the two.
