### ISSUE TITLE
Make it easier to reference drop credentials into the bundle directory

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#496]
Instead of forcing people to code in the path where their bundle is placed inside the cnab environment, we should have a bundle-dir template variable, just like we do in the Dockerfile.

So that instead of having to copy credentials into my bundle directory like this:
```yaml
credentials:
  - name: gcloud-key-file
    path: /cnab/app/gcloud.json
```

I could do this:
```yaml
credentials:
  - name: gcloud-key-file
    path: "{{ porter.bundle-dir}}/gcloud.json"
```

Alternatively, maybe just using a relative path for the destination should drop it into `/cnab/app`?

```yaml
credentials:
  - name: gcloud-key-file
    path: gcloud.json
```

So when porter processes the paths for parameters and credentials, it would convert relative paths to absolute paths under the bundle directory? 🤔 

When they reference the file later in their bundle it would look like this:

```yaml
install:
  - gcloud:
      description: "Authenticate"
      groups:
        - auth
      command: activate-service-account
      flags:
        key-file: gcloud.json
```

Or later when we have [template functions](https://github.com/deislabs/porter/issues/316) and they need the absolute path:

```yaml
install:
  - gcloud:
      description: "Authenticate"
      groups:
        - auth
      command: activate-service-account
      flags:
        key-file: "{{ porter.path(bundle.credentials.gcloud-key-file) }}"
```
