### ISSUE TITLE
[proposal] Introduce imageMap wiring

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/porter#501]
We have the imageMap section in the `porter.yaml` and it ends up looking something like:

```
imageMap:
  websvc:
      description: "A simple web service"
      imageType: "docker"
      image: "jeremyrickard/devops-days-msp@sha256:85b1a9b4b60a4cf73a23517dad677e64edf467107fa7d58fce9c50e6a3e4c914"
      digest: "sha256:85b1a9b4b60a4cf73a23517dad677e64edf467107fa7d58fce9c50e6a3e4c914"
```

Later on, someone might want to define a step that takes that as a param:

```
 azure:
      description: "Create an ACI Instance"
      type: arm
      template: "arm/aci.json"
      name: "{{ bundle.parameters.server-name }}-aci"
      resourceGroup: "{{ bundle.parameters.backend_storage_resource_group }}"
      parameters:
        containerName: "{{ bundle.parameters.server-name }}-aci-go"
        location: "{{ bundle.parameters.location }}"
        imageName: "jeremyrickard/devops-days-msp@sha256:85b1a9b4b60a4cf73a23517dad677e64edf467107fa7d58fce9c50e6a3e4c914"
        mysqlFQDN: "{{bundle.outputs.mysql_fqdn}}"
        port: "8080"
```

Instead of having to retype/copy paste it, it might be cool if we could reference it like `{{bundle.imageMap.websvc}}` or something along those lines. This might allow us to support the relocation stuff that duffle is doing as well. Porter could take the relocation file and change those references as needed. 

Nothing stops someone from _not_ using that mechanism when it's introduced, but this would be a nice feature to have and we could write some best practice stuff up and encourage people to follow that pattern.

**Comment by carolynvs** [comment]
I think this looks good. But before we add the feature, I'd feel better if we could flesh out the entire workflow end to end of what it would look like for someone to use relocation with porter and put that into issues. Just to make sure that we don't have awkward gaps and make sure that it all gets implemented together.

**Comment by jeremyrickard** [comment]
End to end, this would look something like:

Step 0. Build a bundle with Porter
Step 1. Bundle gets pushed to a registry with cnab-to-oci. This will also push any referenced images to the registry and relocate them (security implications being that it is easier to ensure access to the entire bundle when it lives within a single security boundary). When that happens, a _relocation file_ is generated. This contains a mapping of the name found in the imageMap of the bundle to the new location of the image. With the process, the `digest` doesn't change so eventually that could just be validated.

Step 2. You share the relocation file + the bundle reference with someone who wants to run it. 

Step 3. User that wants to run said bundle provides the relocation file at runtime. Duffle supports this currently. This enables the runtime to override the invocation image and any images found in the image map. Handling the invocation image change is pretty easy, since that's just the tooling's responsibility. Handling the others though, needs to happy inside the invocation image via the relocation file. The relocation file gets mounted into the invocation image and the runtime _should_ then update the references. In our case, I think that comes down to the _mixin_ knowing that to replace, so any mixin that will deal with images probably needs to be updated in order to get passed that new info, probably via a parameter up above (maybe it's just a _best practice_ that you expose those things). 

The same would happen with importing a bundle across an air gap and publishing it up to an internal registry. Consider the scenario where we build a bundle that will use Helm to install some app on a k8s cluster in an airgapped network or a network with a very restrictive network policy. You'd likely need to export the bundle, move it across the gap and then import it and publish all the images. At that point, the helm chart needs to have the values for whatever images it will use be updated to point to these new places (obviously the chart needs to be in the bundle as well). 

I'll open another issue for supporting the relocation file.

**Comment by radu-matei** [comment]
Right now that's not configurable, no - when you push a bundle, to a repository, all images will be copied to that repository.

That being said, I don't necessarily like this behaviour of `cnab-to-oci` - what would be your ideal workflow?

**Comment by jeremyrickard** [comment]
Another useful thing that might be useful with the wiring is the ability to do something of the form:

```
{{bundle.imageMap.websvc.registry}}
```

and 

```
{{bundle.imageMap.websvc.tag}}
```

and maybe:

```
{{bundle.imageMap.websvc.digest}}
```

Each of these would give you back the appropriate portion of the image? I think it's fairly common for Helm charts to have the image broken down like:

```
image:
  repository: gcr.io/mcguffin-co/mcguffin
  tag: v1.1.0
  pullPolicy: IfNotPresent
```

In which case, the pieces of the image reference are more useful than the entire thing.

**Comment by carolynvs** [comment]
Oooh yeah good point. I think then maybe we'd want the imageMap section to ultimately look like this (I'm doing a full makeover):

```yaml
images:
  ALIAS:
    description: A very useful image
    imageType: docker # porter.yaml can default this to docker if we aren't already
    repository: gcr.io/mcguffin-co/mcguffin
    digest: sha256:85b1a9 # this is what bundle.json allows
    tag: v1.1.0 # we can collect this and make it available but it won't land into bundle.json
```

When we have template functions, I'd want to add one that knows how to work off of an image map entry and give you the either the tag or digest concatenated:

```yaml
imageWithDigest: "{{ digestRef bundle.images.ALIAS }}" # gcr.io/mcguffin-co/mcguffin@sha256:85b1a9 
imageWIthTag: "{{ tagRef bundle.images.ALIAS }}" # gcr.io/mcguffin-co/mcguffin:v1.1.0
```
