### ISSUE TITLE
Generate a bundle from a set of assets that a mixin understands

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#531]
People may appreciate being able to bootstrap a bundle from a set of assets that a mixin understands. For example making a bundle from a set of terraform files, or a helm chart. The terraform mixin or helm mixin could say that it knows what to do with these assets and generate an initial bundle.

```console
$ porter create --from-mixin terraform ./tf
A new bundle has been created based on the terraform mixin.
```

```yaml
name: ?
version: ?
tag: ?
invocationImage: ?

mixins:
- terraform

parameters:
... params generated from the terraform 

outputs:
... outputs generated from the terraform

install:
- terraform:
... calls terraform mixin for you based on what was in that source directory

update:
- terraform:
...
uninstall:
...

```

If the command is run in a directory with an existing bundle, and the `--merge` flag is passed, then the manifest is merged, appending parameters, outputs and unique actions and steps.

```console
$ porter create --from-mixin helm ./charts -merge
The existing bundle has been updated based on the helm mixin.
```
