### ISSUE TITLE
Can we support outputs from the exec mixin?

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#539]
We would like to support outputs from the exec mixin. We aren't sure what that would even look like though. In other mixins, there's a clear abstraction for each mixin that mapped onto outputs.

For example with the kubernetes mixin, you specify a resource and a jsonpath. Helm lets you output secrets created by the release.

What would be the output of any arbitrary command?

Perhaps it is letting you scrape the stdout/stderr of the command using jsonpath (similar to the aws and gcloud mixins*) or regex? Grabbing a file? I think it's going to need to be a combination of all three and maybe more.

\* I wrote some nice stuff for the gcloud/aws mixin that I was thinking of moving into the exec mixin. Then all "binary wrapper" mixins could base themselves on the exec mixin and use the same tricks.

Here's something to get us started thinking:

**Grab the subscription ids printed from az**
```yaml
exec:
  command: az
  arguments:
    - accounts
    - list
    - -output=json
  outputs:
    - name: subscriptions
       jsonPath: [*].subscriptionId
```

**Save a file generated by a bash script**
```yaml
exec:
  command: bash
  arguments:
  - ./install.sh
  outputs:
  - name: magic-config
     path: config.toml
```

**Scrape text out of the stdout from a bash script**
```yaml
exec:
  command: bash
  arguments:
  - ./install.sh
  outputs:
  - name: magic-number
     regex: '^magic-number: (/d)+$'
```

**Comment by jeremyrickard** [comment]
I think a related thing to this might be to make _bundle outputs_ able to generate an output from things other than outputs from mixin steps. 

I like the explicit nature of this:

```
exec:
  command: bash
  arguments:
  - ./install.sh
  outputs:
  - name: magic-config
     path: config.toml
```

But if we think of the TF mixin, as an example, other files might get generated..i.e. the TF state file when you use the `local` backend. In that case, you end up with a local tf state file in the invocation image. It's likely that other mixins might produce a file as well. Maybe we can have that bubbled up to bundle outputs more generally? 

```
outputs:
   cool-output-name:
        file: "/some/path/to/file"
``` 

and the current use turns more like:

```
outputs:
   cool-output-name:
        value: "{bundle.outputs.SOMENAME}}"
``` 

The examples above are cool but seem like they might get complicated and might be error prone for users. 

```
