### ISSUE TITLE
Output a file from the bundle in a "bundle level output"

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#540]
I'm splitting off Jeremy's suggestion into it's own issue

https://github.com/deislabs/porter/issues/539#issuecomment-523543480

A bundle output should be able to make an output from a file in the execution environment, not just from existing outputs created by a step.

```yaml
outputs:
  - name: kubeconfig
    description: "Admin kubeconfig file"
    type: file
    applyTo:
      - install
    path: /root/.kube/config
```
