### ISSUE TITLE
Build time configuration of mixins

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#583]
Allow mixins to accept a blob of yaml that they can use to configure the invocation image at build time.

```yaml
mixins:
  - az:
     extensions:
       - custom-extension1
```

alternatively

```yaml
mixins:
  - az

az:
  extensions:
    - custom-extension1
```
