### ISSUE TITLE
Doc how to use gke with porter

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#658]
You need to authenticate your SA in addition to passing the kubeconfig

From Shash Reddy on slack
After some research I found that using combination of GOOGLE_APPLICATION_CREDENTIALS and KUBECONFIG environment variables I dont need gcloud to authenticate to my cluster. I tried that locally to verify and it worked. I tried with porter with exec mixin to setup env vars and authentication did not work. Today I came in and realized there is gcloud mixin plugin(yayyy author) so I tried to use that to authenticate and it worked like magic. This is the final file that worked

```yaml
mixins:
  - exec
  - kubernetes
  - gcloud

parameters:
  - name: name
    type: string
    default: "duffle-test"
  - name: zone-name
    type: string
    default: "us-west1"
  - name: proj-name
    type: string
    default: "test-cluster"

credentials:
  - name: kubeconfig
    path: /root/.kube/config
  - name: gcloud-file
    path: /cnab/app/gcloud.json

name: PORTER_KUBE 
version: 0.1.0
description: "An example Porter bundle with Kubernetes"
invocationImage: deislabs/porter-kubernetes:latest
tag: deislabs/porter-kube-bundle:v0.1.0

install:
  - gcloud:
      description: "Authenticate"
      groups:
        - auth
      command: activate-service-account
      flags:
        key-file: gcloud.json
  - gcloud:
      description: "Authenticate"
      groups:
        - container
        - clusters
      command: get-credentials 
      arguments:
        - "{{ bundle.parameters.name }}"
      flags:
        zone: "{{ bundle.parameters.zone-name }}" 
        project: "{{ bundle.parameters.proj-name }}" 
  - kubernetes:
      description: "Create NGINX Deployment"
      manifests:
        - manifests/nginx
      wait: true
      outputs:
        - name: IP_ADDRESS
          resourceType: service
          resourceName: nginx-deployment
          jsonPath: "{.spec.clusterIP}"

uninstall:
  - gcloud:
      description: "Authenticate"
      groups:
        - auth
      command: activate-service-account
      flags:
        key-file: gcloud.json
  - gcloud:
      description: "Authenticate"
      groups:
        - container
        - clusters
      command: get-credentials 
      arguments:
        - "{{ bundle.parameters.name }}"
      flags:
        zone: "{{ bundle.parameters.zone-name }}" 
        project: "{{ bundle.parameters.proj-name }}" 
  - kubernetes:
      description: "Uninstall Hello World"
      manifests:
        - manifests/nginx
      wait: true

outputs:
  - name: IP_ADDRESS
    type: string
```

See https://ahmet.im/blog/authenticating-to-gke-without-gcloud/
