### ISSUE TITLE
Porter doesn't validate `digest` format, builds bad bundle.json 

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/porter#704]
## Describe the bug

Porter currently uses the `images` section of the `porter.yaml` to build the `images` section of the `bundle.json`. We are currently building the image reference in the `bundle.json` by combining the `repository` and `digest` fields of our YAML document. We don't currently validate the format of the digest, however, which can lead to bad reference strings. For example:

```
images:
  blah:
    repository: jeremyrickard/spring-music
    tag: latest
    digest: 8f1133d81f1b078c865cdb11d17d1ff15f55c449d3eecca50190eed0f5e5e26f
```

That yields a docker reference like:

```
jeremyrickard/spring-music@8f1133d81f1b078c865cdb11d17d1ff15f55c449d3eecca50190eed0f5e5e26f
```

The porter.yaml should really be:

```
images:
  blah:
    repository: jeremyrickard/spring-music
    tag: latest
    digest: sha256:8f1133d81f1b078c865cdb11d17d1ff15f55c449d3eecca50190eed0f5e5e26f
```

We should validate the `digest` format before building the bundle.json and error out if an invalid format is provided. A proper digest includes the algorithm.

Docker's reference code specifies:

```
//	digest                          := digest-algorithm ":" digest-hex
//	digest-algorithm                := digest-algorithm-component [ digest-algorithm-separator digest-algorithm-component ]*
//	digest-algorithm-separator      := /[+.-_]/
//	digest-algorithm-component      := /[A-Za-z][A-Za-z0-9]*/
//	digest-hex                      := /[0-9a-fA-F]{32,}/ ; At least 128 bit digest value
```

## To Reproduce
Grab https://gist.github.com/jeremyrickard/60e4b0b0e13e131133e5d73a3130aee8
Run `porter build`
Check the `.cnab/bundle.json`

## Expected behavior

Porter should not have an invalid docker reference string for image.
