### ISSUE TITLE
found unexpected end of stream

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#783]
## Describe the bug
I am getting `found unexpected end of stream` when trying to use templating with quotes in the middle of a string instead of enclosing the entire line.

## To Reproduce

Use the following **porter.yaml**

```yaml
name: HELLO
version: 0.1.0
description: "An example Porter configuration"
invocationImage: porter-hello:latest
tag: deislabs/porter-hello-bundle:latest

mixins:
  - exec

install:
  - exec:
      description: "Install Hello World"
      command: bash
      flags:
        c: echo Hello World

upgrade:
  - exec:
      description: "World 2.0"
      command: bash
      flags:
        c: echo "special output"
      outputs:
        - name: stuff
          regex: (.*)
  - exec:
      description: "Show Outputs"
      command: bash
      flags:
        c: echo "{{ bundle.outputs.stuff }}"

uninstall:
  - exec:
      description: "Uninstall Hello World"
      command: bash
      flags:
        c: echo Goodbye World
```

1. Run `porter install`
2. Run `porter upgrade`

## Expected behavior
I expected to see 

```
upgrading HELLO...
executing upgrade action from HELLO (bundle instance: HELLO) defined in /cnab/app/porter.yaml
World 2.0
special output
Show Outputs
*******execution completed successfully!
```

But instead I get the following:

```
upgrading HELLO...
executing upgrade action from HELLO (bundle instance: HELLO) defined in /cnab/app/porter.yaml
World 2.0
special output
Error: unable to resolve sourced values: unable to resolve step: invalid step yaml: yaml: line 7: found unexpected end of stream
Error: 1 error occurred:
	* failed to upgrade the bundle: container exit code: 1, message: <nil>
```

When I alter the **porter.yaml** slightly to enclose my use of the `{{ }}` from

```
c: echo "{{ bundle.outputs.stuff }}"
```
to this

```
c: "echo {{ bundle.outputs.stuff }}"
```

it works but I'm not confident that workaround should be required in this case.

Porter should check during build that the **porter.yaml** file has valid template syntax, including that the `{{ }}` are enclosed with double quotes properly so that it doesn't blow up like this at runtime. Also this bug should help out anyone searching on this error string later.

## Version
Copy the output of `porter version` below

porter v0.20.2-beta.1-9-gdebe787 (debe787)
