### ISSUE TITLE
[New Request] Positional arguments

### ISSUE THREAD

**Issue by nunix** [deislabs/porter#806]
## Describe the bug
For using commands with the new `arguments` and `flags` options, there would be the need to have arguments and/or flags to be "positioned" at the end (for example)

## To Reproduce
In a bundle, using `ssh` with the need to have a command at the end is currently not possible using the "clean" way.

The original command (read: outside a bundle) is:
`ssh host -l username -p port uname`

Currently, here is how the command would be translated using `arguments` and `flags`:
```
command: ssh
arguments:
   - host
flags:
   l: "username"
   p: "port"
```

as the arguments cannot be called again, the last command is not possible to insert.
Instead, today there would be the need to call the command within a shell call:

```
command: bash
flags:
   c: "ssh host -l username -p port uname"
```

## Expected behavior
Based on the examples above, I would hope something like this would be possible:

```
command: ssh
arguments:
   - host
   - command:
      postion: after=flags=p / last/ <position X>
flags:
   l: username
   p: port
```

## Porter Command and Output
N/A

## Version
Copy the output of `porter version` below

porter v0.20.2-beta.1 (3df87f1)

Hope this will make sense and thanks a lot for work ♥
