### ISSUE TITLE
Failed to install bundle with a dependency

### ISSUE THREAD

**Issue by MikeLarah** [deislabs/porter#819]
## Describe the bug
Running `porter install` on bundle with a child dependency results in the following error:
```
Error: 1 error occurred:
        * failed to install the bundle: error staging files: destination path \cnab\app\dependencies\dependency-child-1\bundle.json should be an absolute unix path
```

## To Reproduce

1. Use the following porter manifests:

dependency-parent
```
name: dependency-parent
version: 0.1.0
description: dependency-parent
invocationImage: ***.azurecr.io/porter/dependency-parent:0.1.0
tag: ***.azurecr.io/porter/dependency-parent/bundle:0.1.0

parameters:
- name: parent_param
  type: string
  description: parent_param

dependencies:
  dependency-child-1:
    tag: ***.azurecr.io/porter/dependency-child-1/bundle:0.1.0
    parameters:
      child_1_param: "{{ bundle.parameters.parent_param }}"

mixins:
  - exec

install:
  - exec: 
      description: "Install step"
      command: "bash"
      arguments:
        - "-c"
        - |
          echo '[from: dependency-parent] [param: dependency-parent.parent_param] = {{ bundle.parameters.parent_param }}'
          echo '[from: dependency-parent] [output: dependency-child-1.child_1_output] = {{ bundle.dependencies.dependency-child-1.outputs.child_1_output }}'

uninstall:
  - exec: 
      description: "Uninstall step"
      command: "bash"
      arguments:
        - "-c"
        - "echo 'Uninstalling!'"
```

dependency-child
```
name: dependency-child-1
version: 0.1.0
description: dependency-child-1
invocationImage: ***.azurecr.io/porter/dependency-child-1:0.1.0
tag: ***.azurecr.io/porter/dependency-child-1/bundle:0.1.0

parameters:
- name: child_1_param
  type: string
  description: child_1_param

mixins:
  - exec

install:
  - exec: 
      description: "Install step"
      command: "bash"
      arguments:
        - "-c"
        - |
          echo '{{ bundle.parameters.child_1_param }} + child_1' > child_1_output_file
          echo '[from: dependency-child-1] [param: dependency-child-1.child_1_param] = {{ bundle.parameters.child_1_param }}'
      outputs:
        - name: child_1_output
          path: child_1_output_file

uninstall:
  - exec: 
      description: "Uninstall step"
      command: "bash"
      arguments:
        - "-c"
        - "echo 'Uninstalling!'"
    
outputs:
  - name: child_1_output
    type: string
    applyTo:
      - install
```
2.  Run `porter install --param parent_param=foo,dependency-child-1#child_1_param=bar` for the dependency-parent bundle from PowerShell on Windows 10 

## Expected behavior
Bundle should run install action

## Porter Command and Output
```
$ porter install --param parent_param=foo,dependency-child-1#child_1_param=bar
Building bundle ===>
Copying porter runtime ===> 
Copying mixins ===> 
Copying mixin exec ===> 

Generating Dockerfile =======>

Writing Dockerfile =======>

Starting Invocation Image Build =======>
Executing dependency dependency-child-1...
executing install action from dependency-child-1 (bundle instance: dependency-parent-dependency-child-1)
Install step
[from: dependency-child-1] [param: dependency-child-1.child_1_param] = bar
execution completed successfully!
installing dependency-parent...
Error: 1 error occurred:
        * failed to install the bundle: error staging files: destination path \cnab\app\dependencies\dependency-child-1\bundle.json should be an absolute unix path
```

## Version
Copy the output of `porter version` below

porter v0.21.0-beta.1-6-g6411991 (6411991)
