### ISSUE TITLE
output from previous action cannot be used

### ISSUE THREAD

**Issue by ffoysal** [deislabs/porter#834]
a sample `porter.yaml` is
```
outputs:
- name: kubeconfig
  description: "Kubeconfig for the newly created "
  type: string
  applyTo:
  - install
  - upgrade
  - uninstall
install:
  - exec:
      description: "Display Cluster info"
      command: bash
      flags:
        c: cat /root/.kube/config
      outputs:
      - name: kubeconfig
        path: /root/.kube/config
uninstall:
  - exec:
      description: "Uninstalling: get kubeconfig from outputs"
      command: bash
      flags:
        c: "echo {{ bundle.outputs.kubeconfig }} > /root/.kube/config" 
```
after install I can see the output using `porter instances output show kubeconfig -i hack`
when I do `porter uninstall hack` got this
```
uninstalling hack...
executing uninstall action from Test (bundle instance: hack)
Error: unable to resolve sourced values: unable to resolve step: unable to render template exec:
  command: bash
  description: 'Uninstalling: get kubeconfig from outputs'
  flags:
    c: "echo {{ bundle.outputs.kubeconfig }} > /root/.kube/config"
: Missing variable "kubeconfig"
Error: failed to uninstall the bundle: container exit code: 1, message: <nil>. fetching outputs failed: error copying outputs from container: Error: No such container:path: 2f4ab208d54d3d9fc6d96e70faf62c73c43e3c0413da180f2c584400a0b18095:/cnab/app/outputs
```
any idea ??
