### ISSUE TITLE
double quote in the value of parameters is not encoded properly

### ISSUE THREAD

**Issue by ffoysal** [deislabs/porter#846]
This is porter.yaml
```
# This is the configuration for Porter
# You must define steps for each action, but the rest is optional
# See https://porter.sh/author-bundles for documentation on how to configure your bundle
# Uncomment out the sections below to take full advantage of what Porter can do!

name: HELLO
version: 0.1.0
description: "An example Porter configuration"
invocationImage: porter-hello:latest
tag: deislabs/porter-hello-bundle:latest

# Uncomment out the line below to use a template Dockerfile for your invocation image
#dockerfile: Dockerfile.tmpl

mixins:
  - exec

parameters:
  - name: myConfigs
    description: "Config for keycloak"
    type: string
    default: '[{"discoveryUrl":"http://keycloak-insecure:8089/keycloak/realms/master22/.well-known/openid-configuration","clientId":"edge-auth"}]]'
    
install:
  - exec:
      description: "Install Hello World"
      command: bash
      flags:
        c: echo "{{bundle.parameters.myConfigs}}"

upgrade:
  - exec:
      description: "World 2.0"
      command: bash
      flags:
        c: echo World 2.0

uninstall:
  - exec:
      description: "Uninstall Hello World"
      command: bash
      flags:
        c: echo Goodbye World


# See https://porter.sh/author-bundles/#dependencies
#dependencies:
#  mysql:
#    tag: deislabs/porter-mysql:latest
#    parameters:
#      database-name: wordpress

# See https://porter.sh/wiring/#credentials
#credentials:
#  - name: kubeconfig
#    path: /root/.kube/config
```
when run `porter install` it produces the output
```
installing HELLO...
executing install action from HELLO (bundle instance: HELLO)
Install Hello World
[{&#34;discoveryUrl&#34;:&#34;http://keycloak-insecure:8089/keycloak/realms/master22/.well-known/openid-configuration&#34;,&#34;clientId&#34;:&#34;edge-auth&#34;}]]
execution completed successfully!
```
See the double quote `"` is replaced by `&#34;`
