### ISSUE TITLE
Allow for non-sensitive step outputs

### ISSUE THREAD

**Issue by vdice** [deislabs/porter#855]
It may be convenient to support a `sensitive` field on a step output (that itself is not a bundle-level output) with a value of either `true` or `false`, just like bundle-level outputs can declare.  Then, we can either continue to mask this output value in logs if `sensitive: true` and not mask if `sensitive: false`.

Currently, step outputs that aren't declared as bundle-level outputs have differing data representations depending on which mixin they are meant for.  Other than that, there are no similar fields that porter attempts to parse out.  Therefore, this change may require a bit of rewiring and persistence of a structured representation of each output when unmarshal-ing.

**Comment by jeremyrickard** [comment]
Super in favor of this!

**Comment by carolynvs** [comment]
```yaml
install:
  - exec:
       command: cat
       arguments:
         - some/file.txt
       outputs:
         - name: myfile # this is a step output, "mixin generate output"
            regex: "..."
            sensitive: true # this is a new field. It defaults to false which is a behavior change in porter which is why it's getting done before v1.0

outputs:
  - name: myfile # promotes a step output to a bundle output
     # If they set sensitive on the bundle output, use that value. Otherwise use the step output's sensitive value.
```
