### ISSUE TITLE
Parameters for dependent bundles aren't passed

### ISSUE THREAD

**Issue by brandonjbjelland** [deislabs/porter#924]
## Describe the bug

Originally described [on a related issue](https://github.com/deislabs/porter/issues/801#issuecomment-586557588).

I'm unable to pass parameters to dependent bundles as demonstrated in the [wordpress examples](https://github.com/deislabs/porter/blob/master/build/testdata/bundles/wordpress/porter.yaml#L9-L14). Passing parameters works as expected when passing directly to a local or tag-based top-level bundle, just not when piping those through to the child bundles. This [repro repo](https://github.com/brandonjbjelland/cnab-experiments/tree/master/dependency-params-bug) gives more detail.

## To Reproduce

Repo with the test case [is here](https://github.com/brandonjbjelland/cnab-experiments/tree/master/dependency-params-bug). Steps to reproduce the behavior:

1. create a simple child bundle that accepts parameters and publish it:

```yaml
name: cnab-exec-component
version: 0.3.0
invocationImage: ***/cnab-exec-component:v0.3.0
tag: ***/cnab-exec-component:v0.3.0
dockerfile: Dockerfile.tmpl

parameters:
  - name: environment
    type: string
    default: dev
  - name: somearg
    type: string
    default: foo
...
```

2. Create a parent bundle that passes parameters to that child, calling the child bundle by tag:

```yaml
name: cnab-parent-component
version: 0.1.0
invocationImage: ***/cnab-parent-component:v0.1.0
tag: ***/cnab-parent-component:v0.1.0

parameters:
  - name: somearg
    type: string
    default: baz
  - name: environment
    type: string
    default: qa

dependencies:
  exec-child:
    tag: brandoconnor/cnab-exec-component:v0.3.0
    parameters:
      somearg: "{{ bundle.parameters.somearg }}"
      environment: "{{ bundle.parameters.environment }}"
...
```

Install the parent bundle:

```bash
$ cd cnab-parent-component
# executing the bundle with environment=prod
$ porter install --param environment=prod
Executing dependency exec-child...
executing install action from cnab-exec-component (bundle instance: cnab-parent-component-exec-child)
Testing variable IO within dependency
{
  "action": "install",
  "environment": "dev",
  "somearg": "foo"
}
```

## Expected behavior

I expect the parent to pass parameters to dependent bundles as declared. As it stands, only the defaults on the child bundle are ever passed. If a required variable is on the child bundle, I believe it's impossible to pass.

## Version

```bash
porter version                
porter v0.23.0-beta.1-8-g2eb38e9 (2eb38e9)
```
