### ISSUE TITLE
exec mixin adding line break with use of output from previous step, blows yaml at rendering

### ISSUE THREAD

**Issue by squillace** [deislabs/porter#936]
## Describe the bug
Reuse of an output from a previous step introduces a line break in the rendered yaml, blowing up the pipeline.

## To Reproduce
1. The following yaml (from this repository: https://github.com/squillace/microservices-reference-implementation)
```yaml
  - exec:
      command: bash
      description: "IDENTITIES_DEPLOYMENT_NAME"
      flags:
        c: az deployment show -n azuredeploy-prereqs-dev --query properties.outputs.identitiesDeploymentName.value -o tsv
      outputs:
        - name: IDENTITIES_DEPLOYMENT_NAME
          regex: "(.*)"
  - exec:
      command: bash
      description: "testing for a space"
      flags:
        c: echo \"{{bundle.outputs.IDENTITIES_DEPLOYMENT_NAME}}\"
```

2. Results in the following error:
```
=== Rendered Step ===
exec:
  command: bash
  description: testing for a space
  flags:
    c: echo \"azuredeploy-prereqs-dev-identities
\"

Error: unable to resolve step: invalid step yaml
exec:
  command: bash
  description: testing for a space
  flags:
    c: echo \"azuredeploy-prereqs-dev-identities
\"
: yaml: line 7: could not find expected ':'
```

Below is the full error stack.
```
IDENTITIES_DEPLOYMENT_NAME
DEBUG name:    exec
DEBUG pkgDir: /cnab/app/mixins/exec
DEBUG file:     
DEBUG stdin:
install:
- exec:
    command: bash
    description: IDENTITIES_DEPLOYMENT_NAME
    flags:
      c: az deployment show -n azuredeploy-prereqs-dev --query properties.outputs.identitiesDeploymentName.value
        -o tsv
    outputs:
    - name: IDENTITIES_DEPLOYMENT_NAME
      regex: (.*)

/cnab/app/mixins/exec/exec-runtime install --debug
DEBUG Parsed Input:
&exec.Action{Steps:[]exec.Step{exec.Step{Instruction:exec.Instruction{Description:"IDENTITIES_DEPLOYMENT_NAME", Command:"bash", Arguments:[]string(nil), Flags:builder.Flags{builder.Flag{Name:"c", Values:[]string{"az deployment show -n azuredeploy-prereqs-dev --query properties.outputs.identitiesDeploymentName.value -o tsv"}}}, Outputs:[]exec.Output{exec.Output{Name:"IDENTITIES_DEPLOYMENT_NAME", FilePath:"", JsonPath:"", Regex:"(.*)"}}}}}}
bash -c az deployment show -n azuredeploy-prereqs-dev --query properties.outputs.identitiesDeploymentName.value -o tsv
azuredeploy-prereqs-dev-identities
Processing regex output IDENTITIES_DEPLOYMENT_NAME...=== Step Data ===
map[bundle:map[credentials:map[SP_APP_ID:******* SP_CLIENT_SECRET:******* SP_OBJECT_ID:******* SSH_PUBLIC_KEY_FILE:******* SUBSCRIPTION_ID:******* SUBSCRIPTION_NAME:******* TENANT_ID:*******] dependencies:map[] description:A bundle to deliver the basic infrastructure portion of the Microsoft Patterns & Practices Microservices Reference Implementation located at https://github.com/mspnp/microservices-reference-implementation . Full documentation for this implementation can be read at https://docs.microsoft.com/azure/architecture/microservices/.  images:map[] invocationImage:squillace/mspnp-infra-install:v0.1.0 name:microservices-reference-infra-basic outputs:map[IDENTITIES_DEPLOYMENT_NAME:azuredeploy-prereqs-dev-identities
] parameters:map[LOCATION:westus2 RESOURCE_GROUP:mspnp-ref-impl] version:0.1.0]]
=== Step Template ===
exec:
  command: bash
  description: testing for a space
  flags:
    c: echo \"{{bundle.outputs.IDENTITIES_DEPLOYMENT_NAME}}\"

=== Rendered Step ===
exec:
  command: bash
  description: testing for a space
  flags:
    c: echo \"azuredeploy-prereqs-dev-identities
\"

Error: unable to resolve step: invalid step yaml
exec:
  command: bash
  description: testing for a space
  flags:
    c: echo \"azuredeploy-prereqs-dev-identities
\"
: yaml: line 7: could not find expected ':'
Resolved storage plugin to storage.porter.filesystem
/home/ralph/.porter/porter plugin run storage.porter.filesystem
Error: 1 error occurred:
        * failed to install the bundle: container exit code: 1, message: <nil>
```

4. See error above

## Expected behavior
`"azuredeploy-prereqs-dev-identities"`

## Porter Command and Output
```
$ porter install -c credsfile

lots of output
```

## Version
Copy the output of `porter version` below

porter v0.23.0-beta.1 (9c49056)
