### ISSUE TITLE
Set Required Extensions in porter.yaml

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#973]
When a bundle author is composing their porter.yaml file, they may realize that their bundle absolutely needs X, like Docker, in order to run properly. In the CNAB Spec, the way to communicate this is through required extensions. We'd like to make it easy to define the set of required extensions that your bundle needs (from the list of extensions that Porter supports).

```yaml
name: mybun

# custom is still just for authors defining rando data that they want to shove into their bundle metadata. Porter and other bundles don't drive behavior from it
custom:
  customer-specific: special label

# required is the list of required extensions
required:
  # (The name in the spec is probably `io.cnab.docker`, they can use full name to disambiguate, but Porter matches on last part to help out, just like we do with custom actions)
  - docker: 
      # config data can be provided
      privilged: true
  - hypervisor
  - vpn:
       name: mytrustednetwork
```

This gives us space in the future for additional required extensions down the road, like connecting the bundle to the underlying hypervisor or to a trusted network.
