### ISSUE TITLE
Passing a credential file via 'porter install --cred' no longer works

### ISSUE THREAD

**Issue by JamesDawson** [deislabs/porter#988]
## Description
The help text for the `--cred` option for `porter install` says:

> May be either a named set of credentials or a filepath

Since the work to implement storage providers, using a file path no longer seems possible.

## To Reproduce

1. Using the [azure-wordpress](https://github.com/deislabs/porter/tree/master/examples/azure-wordpress) example
2. Create the following file `test-cred.yaml`:
```
name: filecred-example
credentials:
- name: AZURE_SUBSCRIPTION_ID
  source:
    env: AZURE_SUBSCRIPTION_ID
- name: AZURE_CLIENT_ID
  source:
    env: AZURE_CLIENT_ID
- name: AZURE_TENANT_ID
  source:
    env: AZURE_TENANT_ID
- name: AZURE_CLIENT_SECRET
  source:
    env: AZURE_SECRET
- name: kubeconfig
  source:
    env: KUBECONFIG
```
3. Run the following command:
```porter install --cred test-cred.yaml```
4. See this error:
```Error: could not load credentials: Credential set does not exist```
5. Re-run the above command specifying the full path instead:
```porter install --cred c:\somepath\test-cred.yaml```
6. See this error:
```Error: could not load credentials: open C:\Users\<username>\.porter\credentials\C:\somepath\test-cred.yaml.json: The filename, directory name, or volume label syntax is incorrect.```

## Expected behavior
The credential is loaded from the file and used as if it were a named credential in the store.

## Version
```porter v0.26.0-beta.1 (b15c4109)```
